name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Build Using TeXLive
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 0.main.tex
          latexmk_use_xelatex: true

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: paper
          path: 0.main.pdf
